# Generated by Django 5.1.6 on 2025-11-30 17:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_host', models.BooleanField(default=False, help_text='Indicates whether the user is a bike host.')),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number (optional).", max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Nepal number (e.g., '+9779841234567').", regex='^\\+977\\d{9}$')])),
                ('address', models.TextField(blank=True, help_text="User's address (optional).", null=True)),
                ('profile_picture', models.ImageField(default='default_user.jpg', help_text='Profile image uploaded by the user.', upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, help_text='User’s date of birth (optional).', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short description about the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BikehostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_make', models.CharField(help_text='Make of the bike (e.g., Hero, Yamaha).', max_length=100)),
                ('bike_model', models.CharField(help_text='Model of the bike (e.g., Splendor, FZ).', max_length=100)),
                ('bike_year', models.PositiveIntegerField(help_text='Manufacturing year of the bike.')),
                ('bike_registration_number', models.CharField(help_text='Bike registration number.', max_length=20, unique=True)),
                ('registration_certificate', models.FileField(help_text='Upload bike registration certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_host_requests/'), upload_to='bike_host_requests/bike_docs/registration/')),
                ('insurance_certificate', models.FileField(help_text='Upload bike insurance certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_host_requests/'), upload_to='bike_host_requests/bike_docs/insurance/')),
                ('id_proof', models.FileField(help_text='Upload user ID proof (e.g., driver’s license).', storage=django.core.files.storage.FileSystemStorage(location='media/bike_host_requests/'), upload_to='bike_host_requests/bike_docs/id_proof/')),
                ('bike_photos', models.ImageField(help_text='Upload photos of the bike.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_host_requests/'), upload_to='bike_host_requests/bike_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Request status.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was submitted.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was reviewed.', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the admin during review.', null=True)),
                ('user', models.ForeignKey(help_text='User submitting the request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_details', models.TextField(blank=True, help_text='Bank account information for payouts.', null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text="Total number of bookings made for the host's bikes.")),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total earnings from all bookings.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('user', models.OneToOneField(help_text='User associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
