# Generated by Django 5.1.6 on 2025-02-14 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='earnings',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number (optional).", max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Nepal number (e.g., '+9779841234567').", regex='^\\+977\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', help_text='Profile image uploaded by the user.', upload_to='profile_pictures/'),
        ),
    ]
