# Generated by Django 5.1.6 on 2025-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ownerprofile_earnings_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_user.jpg', help_text='Profile image uploaded by the user.', upload_to='profile_pictures/'),
        ),
    ]
