# Generated by Django 5.1.6 on 2026-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nationality_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license_no',
            field=models.CharField(blank=True, help_text="User's driving license number.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_no',
            field=models.CharField(blank=True, help_text="User's passport number.", max_length=50, null=True),
        ),
    ]
