# Generated by Django 5.1.6 on 2025-03-11 11:39

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeOwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_make', models.CharField(help_text='Make of the bike (e.g., Hero, Yamaha).', max_length=100)),
                ('bike_model', models.CharField(help_text='Model of the bike (e.g., Splendor, FZ).', max_length=100)),
                ('bike_year', models.PositiveIntegerField(help_text='Manufacturing year of the bike.')),
                ('bike_registration_number', models.CharField(help_text='Bike registration number.', max_length=20, unique=True)),
                ('registration_certificate', models.FileField(help_text='Upload bike registration certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_docs/registration/')),
                ('insurance_certificate', models.FileField(help_text='Upload bike insurance certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_docs/insurance/')),
                ('id_proof', models.FileField(help_text='Upload user ID proof (e.g., driver’s license).', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_docs/id_proof/')),
                ('bike_photos', models.ImageField(help_text='Upload photos of the bike.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Request status.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was submitted.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was reviewed.', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the admin during review.', null=True)),
                ('user', models.ForeignKey(help_text='User submitting the request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
