# Generated by Django 5.1.6 on 2025-03-14 04:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bikeownerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeownerrequest',
            name='bike_photos',
            field=models.ImageField(help_text='Upload photos of the bike.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_owner_requests/bike_photos/'),
        ),
        migrations.AlterField(
            model_name='bikeownerrequest',
            name='id_proof',
            field=models.FileField(help_text='Upload user ID proof (e.g., driver’s license).', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_owner_requests/bike_docs/id_proof/'),
        ),
        migrations.AlterField(
            model_name='bikeownerrequest',
            name='insurance_certificate',
            field=models.FileField(help_text='Upload bike insurance certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_owner_requests/bike_docs/insurance/'),
        ),
        migrations.AlterField(
            model_name='bikeownerrequest',
            name='registration_certificate',
            field=models.FileField(help_text='Upload bike registration certificate.', storage=django.core.files.storage.FileSystemStorage(location='media/bike_owner_requests/'), upload_to='bike_owner_requests/bike_docs/registration/'),
        ),
    ]
