# Generated by Django 5.1.6 on 2025-02-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for the booking.', max_digits=10)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('esewa', 'eSewa')], help_text='Payment method used (e.g., PayPal, eSewa).', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the payment.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the payment was initiated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('booking', models.OneToOneField(help_text='Booking associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
