# Generated by Django 5.1.6 on 2025-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('esewa', 'eSewa'), ('cash_on_delivery', 'Cash on Delivery')], help_text='Select payment method', max_length=50),
        ),
    ]
