# Generated by Django 5.1.6 on 2025-02-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique Transaction ID from the payment gateway.', max_length=100, null=True, unique=True),
        ),
    ]
