# Generated by Django 5.1.6 on 2025-12-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_payment_option'),
        ('payment', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the invoice was generated.')),
                ('booking', models.OneToOneField(help_text='Booking associated with this invoice.', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
            ],
        ),
    ]
