# Generated by Django 5.1.6 on 2026-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the payment.', max_length=20),
        ),
    ]
