# Generated by Django 5.1.6 on 2025-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_payment_method'),
        ('payment', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='Unique transaction UUID from eSewa payment gateway.', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='payment_pay_booking_dc1489_idx'),
        ),
    ]
