# Generated by Django 5.1.6 on 2025-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the message.', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the person submitting the message.', max_length=254)),
                ('contact_number', models.CharField(help_text='Contact number of the person submitting the message.', max_length=15)),
                ('message', models.TextField(help_text='The message submitted via the contact form.', max_length=1000)),
                ('reply', models.TextField(blank=True, help_text="Admin's reply to the message.", max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the message was submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
            ],
        ),
    ]
