# Generated by Django 5.1.6 on 2025-02-12 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0002_alter_bike_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the issue.', max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', help_text='Current status of the issue.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the issue was reported.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('bike', models.ForeignKey(blank=True, help_text='Bike associated with the issue (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='bikes.bike')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who reported the issue.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
