# Generated by Django 5.1.6 on 2025-02-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bike',
            field=models.ForeignKey(blank=True, help_text='Bike associated with the issue (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='bikes.bike'),
        ),
    ]
