# Generated by Django 5.1.6 on 2026-01-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('bookings', '0003_alter_booking_payment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Nepali', max_length=50)),
                ('driving_license_no', models.CharField(blank=True, max_length=50)),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('chassis_no', models.CharField(blank=True, max_length=100)),
                ('engine_no', models.CharField(blank=True, max_length=100)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_address', models.CharField(blank=True, max_length=255)),
                ('guarantor_phone', models.CharField(blank=True, max_length=20)),
                ('helmet', models.BooleanField(default=False)),
                ('bungy_cord', models.BooleanField(default=False)),
                ('maps', models.BooleanField(default=False)),
                ('deposit_passport', models.BooleanField(default=False)),
                ('deposit_citizenship', models.BooleanField(default=False)),
                ('deposit_id_card', models.BooleanField(default=False)),
                ('deposit_other', models.CharField(blank=True, max_length=100)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking')),
            ],
        ),
    ]
