# Generated by Django 5.1.6 on 2026-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_rentalcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='deposit_citizenship',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='deposit_id_card',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='deposit_other',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='deposit_passport',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='rate_per_day',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='total_amount',
        ),
    ]
