# Generated by Django 5.1.6 on 2026-01-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_rentalcontract_advance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='bungy_cord',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='guarantor_address',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='guarantor_name',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='guarantor_phone',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='helmet',
        ),
        migrations.RemoveField(
            model_name='rentalcontract',
            name='maps',
        ),
    ]
