# Generated by Django 5.1.6 on 2026-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_rentalcontract_bungy_cord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='bungy_cord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='deposit_citizenship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='deposit_id_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='deposit_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='deposit_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='System calculated discount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='guarantor_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='guarantor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='guarantor_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='helmet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional manual discount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='maps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='rate_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='chassis_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='vehicle_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='vehicle_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
