# Generated by Django 5.1.6 on 2025-02-18 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether the testimonial is approved by the admin.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether the testimonial is featured on the homepage.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating given by the user (1–5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
