# Generated by Django 5.1.6 on 2025-02-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start date of the rental period.')),
                ('end_date', models.DateTimeField(help_text='End date of the rental period.')),
                ('pickup_location', models.CharField(help_text='Location where the bike will be picked up.', max_length=200)),
                ('rental_duration', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Rental duration (e.g., hourly, daily, weekly).', max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total rental cost.', max_digits=10, null=True)),
                ('payment_status', models.BooleanField(default=False, help_text='Indicates whether the payment is completed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the booking was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('bike', models.ForeignKey(help_text='Bike being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bikes.bike')),
            ],
        ),
    ]
