# Generated by Django 5.1.6 on 2025-11-30 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating given by the user (1–5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, default='No additional comments.', help_text='Additional comments from the user.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the feedback was submitted.')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start date of the rental period.')),
                ('end_date', models.DateTimeField(help_text='End date of the rental period.')),
                ('pickup_location', models.CharField(help_text='Location where the bike will be picked up.', max_length=200)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total rental cost.', max_digits=10, null=True)),
                ('payment_status', models.BooleanField(default=False, help_text='Indicates whether the payment is completed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking.', max_length=20)),
                ('payment_option', models.CharField(choices=[('full_online', 'Full Payment Online'), ('partial_online', 'Partial Payment Online'), ('cash_on_delivery', 'Cash on Delivery')], default='full_online', help_text='User’s chosen payment method.', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Cash on Delivery')], help_text='Selected payment method (eSewa, PayPal, or Cash on Delivery).', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the booking was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the booking is active.')),
                ('bike', models.ForeignKey(help_text='Bike being booked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bikes.bike')),
            ],
        ),
    ]
