# Generated by Django 5.1.6 on 2025-02-13 10:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating given by the user (1–5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, default='No additional comments.', help_text='Additional comments from the user.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the feedback was submitted.')),
                ('booking', models.OneToOneField(help_text='Booking associated with this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='bookings.booking')),
                ('user', models.ForeignKey(help_text='User who submitted the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
