# Generated by Django 5.1.6 on 2025-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rental_duration',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Rental duration.', max_length=10),
        ),
    ]
