# Generated by Django 5.1.6 on 2025-02-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_is_active_booking_end_date_after_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(choices=[('full_online', 'Full Payment Online'), ('partial_online', 'Partial Payment Online'), ('cash_on_delivery', 'Cash on Delivery')], default='full_online', help_text='User’s chosen payment method.', max_length=20),
        ),
    ]
