# Generated by Django 5.1.6 on 2025-03-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Cash on Delivery')], help_text='Selected payment method (eSewa, PayPal, or Cash on Delivery).', max_length=20, null=True),
        ),
    ]
