# Generated by Django 5.1.6 on 2025-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rental_duration',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='Rental duration.', max_length=10),
        ),
    ]
