# Generated by Django 5.1.6 on 2025-03-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_rental_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rental_duration',
        ),
    ]
