# Generated by Django 5.1.6 on 2025-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bike (e.g., Honda Activa).', max_length=100)),
                ('type', models.CharField(choices=[('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('electric', 'Electric Bike')], help_text='Type of bike.', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Brand of the bike.', max_length=50, null=True)),
                ('model_year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture.', null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, help_text='Mileage of the bike.', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the bike.', max_length=500, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Rental price per day.', max_digits=10)),
                ('availability_status', models.BooleanField(default=True, help_text='Indicates whether the bike is available for booking.')),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates whether the bike is approved by the admin.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark this bike as featured on the homepage.')),
                ('image', models.ImageField(default='default_bike.png', help_text='Image of the bike.', upload_to='bikes/')),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug for the bike.', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the bike was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update.')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('engine_type', models.CharField(blank=True, help_text='Type of engine (e.g., 4-stroke, 2-stroke).', max_length=50, null=True)),
                ('displacement', models.CharField(blank=True, help_text='Engine displacement (e.g., 125 cc).', max_length=20, null=True)),
                ('max_power', models.CharField(blank=True, help_text='Maximum power output (e.g., 8.5 hp).', max_length=20, null=True)),
                ('torque', models.CharField(blank=True, help_text='Torque output (e.g., 10 Nm).', max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, help_text='Transmission type (e.g., Automatic, 5-speed manual).', max_length=50, null=True)),
                ('brakes', models.CharField(blank=True, help_text='Brake system (e.g., Disc/Drum).', max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Bike dimensions (e.g., 1800 x 700 x 1100 mm).', max_length=50, null=True)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Fuel tank capacity in liters (e.g., 5.3 L).', max_digits=5, null=True)),
            ],
        ),
    ]
