# Generated by Django 5.1.6 on 2025-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(help_text='Brand of the bike (e.g., Honda, Yamaha, Royal Enfield).', max_length=50),
        ),
    ]
