# Generated by Django 5.1.6 on 2026-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='chassis_no',
            field=models.CharField(blank=True, help_text='Chassis number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the bike.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_no',
            field=models.CharField(blank=True, help_text='Engine number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number.', max_length=50, null=True),
        ),
    ]
