# Generated by Django 5.1.6 on 2025-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(help_text='Brand of the bike.', max_length=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mileage of the bike.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('electric', 'Electric Bike')], help_text='Type of bike.', max_length=20),
        ),
    ]
