# Generated by Django 5.1.6 on 2025-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_average_rating_alter_bike_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this bike as featured on the homepage.'),
        ),
    ]
