# Generated by Django 5.1.6 on 2026-05-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_chassis_no_bike_color_bike_engine_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='next_maintenance_date',
            field=models.DateField(blank=True, help_text='Automatically calculated date for the next maintenance.', null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='chassis_no',
            field=models.CharField(blank=True, help_text='Chassis Number (VIN). Restricted view.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle Color.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='engine_no',
            field=models.CharField(blank=True, help_text='Engine Number. Restricted view.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle Registration Number (Plate No).', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of maintenance.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the maintenance.', max_digits=10)),
                ('description', models.TextField(help_text='Details of the maintenance work performed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(help_text='Bike that was maintained.', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='bikes.bike')),
            ],
        ),
    ]
