# Generated by Django 5.1.6 on 2025-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brakes',
            field=models.CharField(blank=True, help_text='Brake system (e.g., Disc/Drum).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Bike dimensions (e.g., 1800 x 700 x 1100 mm).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='displacement',
            field=models.CharField(blank=True, help_text='Engine displacement (e.g., 125 cc).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_type',
            field=models.CharField(blank=True, help_text='Type of engine (e.g., 4-stroke, 2-stroke).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fuel tank capacity in liters (e.g., 5.3 L).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='max_power',
            field=models.CharField(blank=True, help_text='Maximum power output (e.g., 8.5 hp).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='torque',
            field=models.CharField(blank=True, help_text='Torque output (e.g., 10 Nm).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='transmission',
            field=models.CharField(blank=True, help_text='Transmission type (e.g., Automatic, 5-speed manual).', max_length=50, null=True),
        ),
    ]
