# Generated by Django 5.1.6 on 2025-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bike_brakes_bike_dimensions_bike_displacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the bike.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the bike.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of manufacture.', null=True),
        ),
    ]
